[package]
name = "usd-render"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bbl-usd = { path = "../bbl-usd-rs" }
gl = "0.14.0"
glam = "0.25.0"
glutin = "0.31.2"
glutin-winit = "0.4.2"
raw-window-handle = "0.5"
winit = { version = "0.29.10", features = ["rwh_05"] }

[build-dependencies]
cfg_aliases = "0.2.0"
gl_generator = "0.14.0"
