[package]
name = "usd-render"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bbl-usd = { path = "../bbl-usd-rs" }
glam = "0.25.0"
